//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailID Already Exists.
        /// </summary>
        internal static string EmailIDValid {
            get {
                return ResourceManager.GetString("EmailIDValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password..
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter UserName..
        /// </summary>
        internal static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recored insert Fail..
        /// </summary>
        internal static string InsertFail {
            get {
                return ResourceManager.GetString("InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recored Inserted Sucessfully..
        /// </summary>
        internal static string InsertSucss {
            get {
                return ResourceManager.GetString("InsertSucss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Fail..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucess..
        /// </summary>
        internal static string LoginSucess {
            get {
                return ResourceManager.GetString("LoginSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recored Found..
        /// </summary>
        internal static string NoRecoredFound {
            get {
                return ResourceManager.GetString("NoRecoredFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recored Found.
        /// </summary>
        internal static string RecoredFound {
            get {
                return ResourceManager.GetString("RecoredFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recored Updated Sucessfully..
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recored Updated fail..
        /// </summary>
        internal static string UpdateSucc {
            get {
                return ResourceManager.GetString("UpdateSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welecome To Eco Chat.
        /// </summary>
        internal static string USERINSERT {
            get {
                return ResourceManager.GetString("USERINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid UserName And Password..
        /// </summary>
        internal static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
    }
}
